.Dd August 25, 2012
.Dt lnkinfo
.Os liblnk
.Sh NAME
.Nm lnkinfo
.Nd determines information about a Windows Shortcut File (LNK)
.Sh SYNOPSIS
.Nm lnkinfo
.Op Fl ahvV
.Va Ar source
.Sh DESCRIPTION
.Nm lnkinfo
is a utility to determine information about a Windows Shortcut File (LNK)
.Pp
.Nm lnkinfo
is part of the
.Nm liblnk
package.
.Nm liblnk
is a library to support the Windows Shortcut File (LNK) format
.Pp
.Ar source
is the source file.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl a
shows allocation information
.It Fl h
shows this help
.It Fl v
verbose output to stderr
.It Fl V
print version
.El
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh EXAMPLES
.Bd -literal
# lnkinfo Calculator.lnk
lnkinfo 20110711

Windows Shortcut information:
	Contains a link target identifier
	Contains a description string
	Contains a working directory string
	Contains an environment variables block

Link information:
	Creation time			: Aug 10, 2004 16:54:24.000000 UTC
	Modification time		: Aug 04, 2004 14:00:00.000000 UTC
	Access time			: Jun 26, 2006 10:36:41.703125 UTC
	Local path			: C:\WINDOWS\system32\calc.exe
	Description			: @%SystemRoot%\system32\shell32.dll,-22531
	Working directory		: C:\WINDOWS\system32
	Environment variables location	: %SystemRoot%\system32\calc.exe

Distributed link tracking data:
	Machine identifier		: hostname
	Droid volume identifier		: f6084ef7-7b6a-41e7-a286-e376c0ffd656
	Droid file identifier		: b7d0e438-4422-48b0-be9d-b4bc8794cef6
	Birth droid volume identifier	: f6084ef7-7b6a-41e7-a286-e376c0ffd656
	Birth droid file identifier	: b7d0e438-4422-48b0-be9d-b4bc8794cef6

.Ed
.Sh DIAGNOSTICS
Errors, verbose and debug output are printed to stderr when verbose output \-v is enabled.
Verbose and debug output are only printed when enabled at compilation.
.Sh BUGS
Please report bugs of any kind to <joachim.metz@gmail.com> or on the project website:
http://code.google.com/p/liblnk/
.Sh AUTHOR
These man pages were written by Joachim Metz.
.Sh COPYRIGHT
Copyright (c) 2009-2012, Joachim Metz <joachim.metz@gmail.com>.
This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.Sh SEE ALSO
